spring.application.name=linknest-api
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/linknest}
spring.data.mongodb.database=linknest
spring.data.mongodb.auto-index-creation=true
app.public-url=${PUBLIC_URL:}
app.frontend-url=${FRONTEND_URL:*}